### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by BreezyMain** [clangd/coc-clangd#261]
When I am trying to call these commands:

```
:CocCommand clangd.update
:CocCommand clangd.install
```

coc.nvim said

```
[coc.nvim] Failed to install clangd language server: Error: Can't fetch release: rate limit exceeded
```

Do anybody has a feasible solution?

**Comment by kadircet** [comment]
Hey @BreezyMain sorry for late reply. This sounds like github limiting your requests. The github's current policy is 60 requests per hour from an unauthenticated client (basically what coc-clangd integration does).

So either you've tried to install clangd lots of times or you are behind a NAT with lots of other people making unauthenticated github REST API calls. In either case this should resolve itself in about an hour.

**Comment by BreezyMain** [comment]
> Hey @BreezyMain sorry for late reply. This sounds like github limiting your requests. The github's current policy is 60 requests per hour from an unauthenticated client (basically what coc-clangd integration does).
> 
> So either you've tried to install clangd lots of times or you are behind a NAT with lots of other people making unauthenticated github REST API calls. In either case this should resolve itself in about an hour.

Thank you!

**Comment by whisperity** [comment]
Unfortunately, my daily work involves sitting behind a NAT where the situation does not resolve itself at all, because servers and CI machines and whatnot will keep making requests, sucking away the rate limit immediately. Could you please perhaps include support for the `GITHUB_TOKEN` environment variable? GitHub's official command-line client, http://github.com/cli/cli supports and respects such a setting.
