### ISSUE TITLE
semanticHighlighting not working anymore

### ISSUE THREAD

**Issue by GiuseppeCesarano** [clangd/coc-clangd#287]
I always had semanticHighlighting enabled with jackguo380/vim-lsp-cxx-highlight and everything was highlighted as intended. Today i updated Coc and all my plugins and i noticed that the highlighting didn't work as intended (only basic keywords are colored like if or int).

**System information**
Clangd version (from the log, or `clangd --version`): 12.0.0
clangd extension version: 0.11.0
Operating system: Arch Linux

**Comment by fannheyward** [comment]
Set `coc.preferences.semanticTokensHighlights` to `false` to disable the new  semanticTokens highlighting, to use the old highlighting protocol.

**Comment by GiuseppeCesarano** [comment]
Still not working. That's my current `coc-settings.json`
```json
{
	"suggest.noselect": false,
	"suggest.enablePreview": true,
	"coc.preferences.colorSupport": true,
	"coc.preferences.semanticTokensHighlights":false,
	"explorer.icon.enableNerdfont": true,
	"clangd.fallbackFlags": [ "-std=c++17" ],
	"clangd.semanticHighlighting": true,
	"markdownlint.config": {
		"default": true,
		"line_length": false
	}
}
```

**Comment by fannheyward** [comment]
Thank you for your feedback, will look into this issue.

**Comment by fannheyward** [comment]
> Client supports legacy semanticHighlights notification and standard semanticTokens request, choosing the latter (no notifications).

clangd supports two semantic highlighting, the old `semanticHighlighting` and the new LSP 3.16.0 `semanticTokens`. When client supports both the two, clangd will only work on the new semanticTokens.

**Comment by GiuseppeCesarano** [comment]
Ye, i just found the commit that disables `semanticHighlighting` if the client supports `semanticTokens`. Do you know why setting `semanticTokensHighlights` to false does not fix the issue? Anyway at this point i almost feel like the problem does not belong there. Clangd should give an option to chose which system use or we simply need to migrate to `semanticTokens`

**Comment by GiuseppeCesarano** [comment]
Also, i wold like to get any type of highlight in my c++ code, so I just tried to set `coc.preferences.semanticTokensHighlights` back to `true` than i added this to my vim settings 
`hi default CocSem_variable ctermfg=Red guifg=#E06C75 cterm=none gui=none` but still my code is  white with some basics keywords colored. I also tried to disabling `clangd.semanticHighlighting`.

Do you have any suggestions on how i cold get highlight in my code?

**Comment by fannheyward** [comment]
Yes, disable `semanticTokensHighlights` doesn't fix this. This need to disable `semanticTokens` feature in client, I'm working on this.

**Comment by wangru-ponyai** [comment]
You can stick to coc.nvim v0.0.80 as a workaround @GiuseppeCesarano .

**Comment by fannheyward** [comment]
semanticTokens is improving in coc side.

**Comment by fannheyward** [comment]
Basic hi groups have been added in coc, please give it a try.

**Comment by GiuseppeCesarano** [comment]
I can confirm that highlighting with semantic tokens now works. Fell free to close this issue.

Is there a way to output the group applied to a certain word? Like vim-lsp-cxx-highlight has `:LspCxxHlCursorSym` to output the group under the cursor

**Comment by fannheyward** [comment]
You can get all tokenTypes by `:call CocActionAsync('showSemanticHighlightInfo')`.

**Comment by GiuseppeCesarano** [comment]
Thanks for the help!

**Comment by Alexey104** [comment]
For me syntax highlighting works again after upgrading coc.nvim to the latest version, but it gets completely broken after any modifications of text:
![Peek 2021-07-09 21-51](https://user-images.githubusercontent.com/38672094/125124416-b4881980-e100-11eb-84bd-a77e86c5e117.gif)

**Comment by CodePurble** [comment]
> For me syntax highlighting works again after upgrading coc.nvim to the latest version, but it gets completely broken after any modifications of text:
> ![Peek 2021-07-09 21-51](https://user-images.githubusercontent.com/38672094/125124416-b4881980-e100-11eb-84bd-a77e86c5e117.gif)

I can confirm this behaviour. Same thing happens for me as well.

**Comment by Alexey104** [comment]
It happens with neovim 0.5.0.

**Comment by GiuseppeCesarano** [comment]
I just tried and it looks like that i get the same behaviour (even with the latest coc release [aa24232](https://github.com/neoclide/coc.nvim/commit/acc2b95be6652d79f86d586e52c7566557608476)). I don't think  reopening this issue would be the best thing since the title says `semanticHighlighting` and this problem is related with `semanticTokens`

**Comment by Alexey104** [comment]
I've opened new [issue](https://github.com/clangd/coc-clangd/issues/298), feel free to join.

**Comment by kostiskalkounos** [comment]
I'm using NVIM 0.5.0 with treesitter for syntax highlighting and I fixed the issue by
setting 
```json 
"coc.preferences.semanticTokensHighlights": false 
```
in cog-settings.json.

**Comment by soratobukuroneko** [comment]
What is the current fix/workaround? I tried downgrading to v0.0.80 but I don't get vim-lsp-cxx-highlight working again.
My conf:

```json
{
    "clangd.arguments": ["--pch-storage=memory", "-j", "20", "--completion-style=detailed", "--background-index", "--all-scopes-completion=true"],
    "clangd.compilationDatabasePath": "build",
    "clangd.fallbackFlags": ["-std=c++2a"],
    "clangd.semanticHighlighting": true
}
```

By the way, is it normal that I have 2 clangs processes started? One with just compile-commands-dir argument, and a second with the args I have set in clangd.arguments. Should'nt I have just one clangd with all the options?

**Comment by soratobukuroneko** [comment]
never mind that. i was running clangd 13. runs fine with clangd 12

**Comment by JingShuWu** [comment]
> I can confirm that highlighting with semantic tokens now works. Fell free to close this issue.
> 
> Is there a way to output the group applied to a certain word? Like vim-lsp-cxx-highlight has `:LspCxxHlCursorSym` to output the group under the cursor
Hi, can you post your configuration,it's still not work on my environment

**Comment by ssh352** [comment]
clang13 user, so what should I do to make it work for clangd 13?

**Comment by Alexey104** [comment]
@ssh352,

init.vim:
```
let g:coc_default_semantic_highlight_groups = 1
```
coc-settings.json:
```
"semanticTokens.filetypes": ["*"],
```

**Comment by ssh352** [comment]
> coc_default_semantic_highlight_groups

@Alexey104 thank you it worked.

also setting
      "coc.preferences.semanticTokensHighlights": true, 
seems fine.
