### ISSUE TITLE
cpp auto complete erro

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [clangd/coc-clangd#330]
```
#include <header>de 
printf(const char *__restrict __format, ...)tf
```
when i use coc-clangd， in the end has word "de" "tf"
clangd version 12.0

**Comment by wangwenqiangGitHub** [comment]
Enter to choose completion item

**Comment by fannheyward** [comment]
Should be fixed on latest coc https://github.com/neoclide/coc.nvim/issues/3290

**Comment by Andoku** [comment]
@fannheyward I am still experiencing this bug.
CocInfo:
```
vim version: VIM - Vi IMproved 8.2 8022681
node version: v16.8.0
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /Users/antontatuev/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

**Comment by fannheyward** [comment]
@Andoku tested with vim 8.2.3350 with latest coc.nvim, can't reproduce this.

**Comment by Andoku** [comment]
@fannheyward But I am still getting this. How can I help to debug this?

**Comment by fannheyward** [comment]
@Andoku please test with minimal vimrc, and provided steps to reproduce this issue.
